name: Run test

on:
  push:
    branches: [ feature ]
  pull_request:
    branches: [ feature ]

env:
  NODE_ENV: production
  PORT: 5000
  MONGODB_URI: ${{ secrets.MONGODB_URI }}

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run lint test
      run: |
        echo "Installing dependencies"
        npm install
        echo "Running lint test"
        npm run lint

    - name: Run tests
      run: |
        echo "Running tests"
        npm run test